# Generated by Django 5.0.1 on 2024-02-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studyresource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyResource',
        ),
    ]
