# Generated by Django 5.0.1 on 2024-02-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_studyresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='studyresource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=255)),
                ('booktitle', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
