# Generated by Django 5.0.1 on 2024-02-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_studyresource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studyresource',
        ),
    ]
