# Generated by Django 5.0.1 on 2024-02-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_studyresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='studyresource',
            fields=[
                ('subjectid', models.AutoField(default='now', primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('chaptername', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=255)),
                ('booktitle', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
