# Generated by Django 5.0.1 on 2024-02-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_studyresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyresource',
            name='subjectid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
